codex/api/urls.py
from . import views
from django.urls import path

app_name = 'api'
urlpatterns = [
    path('api/v0/codex/', views.all),
    path('api/v0/codex/<str:book_num>/', views.content_book),
    path('api/v0/canons/', views.canons),
]

codex/codex/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('api.urls')),
    path('', include('fcontent.urls'))
]

codex/fcontent/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "fcontent"
urlpatterns = [
    path('', views.index, name='index'),
    path('book-1', views.index, name='index'),
    path('book-2', views.index2, name='book2'),
    path('canon-search', views.canon_search, name='canon_search')
]

codex/fcontent/models.py
from django.db import models

# Create your models here.

codex/api/views.py
from pathlib import Path
from django.shortcuts import render
from django.http import JsonResponse
import regex
import pymongo
import json


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

with open(str(BASE_DIR.parent.parent)+"/codex-config.json") as f:
    conf = json.load(f)


def parse_bson(curser):
    out = list(curser)
    l = []
    for i, mass in enumerate(out):
        mass["_id"] = str(mass["_id"])
        l.append(mass)
    return l


def get_num(tag):
    return tag[:tag.find("-")], int(tag[tag.find("-")+1:])


def all(request, format=None):
    client = pymongo.MongoClient(conf["db"])
    db = client["codex"]
    coll = db["api_content"]
    return JsonResponse(list(parse_bson(coll.find()))[0]["book"], safe=False)


def canons(request, format=None):
    client = pymongo.MongoClient(conf["db"])
    db = client["codex"]
    coll = db["canons"]
    out = coll.find()

    return JsonResponse(parse_bson(coll.find()), safe=False)


def content_book(request, book_num):
    client = pymongo.MongoClient(conf["db"])
    db = client["codex"]
    coll = db["api_content"]

    books = ["book-1_general-principles-of-canon-law",
             "book-2_laws-concerning-persons",
             "book-3_sacred-things",
             "book-4_canonical-trials",
             "book-5_offences-and-penalties"]

    for book in books:
        if book.find(book_num) != -1:

            resp = JsonResponse(list(coll.find())[0]["book"][book], safe=False)
            #resp['Access-Control-Allow-Origin'] = "localhost:8000"
            resp['Access-Control-Allow-Origin'] = "http://iudicabit.mywire.org"
            #resp['Access-Control-Allow-Origin'] = "*"
            return resp

codex/fcontent/views.py
from pathlib import Path
from django.shortcuts import render
import requests
from django import template
from django.template.defaultfilters import stringfilter
import pymongo
import json


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

with open(str(BASE_DIR.parent.parent)+"/codex-config.json") as f:
    conf = json.load(f)


def index(request):
    return render(request, "fcontent/index1.html")


def index2(request):
    return render(request, "fcontent/index2.html")


def canon_search(request):
    out = request.GET['search']
    client = pymongo.MongoClient(conf["db"])
    db = client["codex"]
    coll = db["canons"]
    search_list = coll.find(
        {"$text": {"$search": out}})

    return render(request, "fcontent/canon_search.html", {"data": search_list})


"""
h1 = Books
h2 = Parts
h3 = sections
h4 = titles
h5 = chapters
h6 = articles
-- = canons

"""

codex/fcontent/templates/fcontent/canon_search.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>1917 Codex</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="David Lanigan dav.lanigan@gmail.com">    
    <link rel="shortcut icon" href="favicon.ico">  
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel='stylesheet' type='text/css'>
    <!-- FontAwesome JS -->
    <script defer src={% static "assets/fontawesome/js/all.js" %}></script>
    <!-- Global CSS -->
    <link rel="stylesheet" href={% static "assets/plugins/bootstrap/css/bootstrap.min.css" %}>   
    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href={% static "assets/css/styles.css" %}>
    
    <style>

        html, body, div, span, applet, object, iframe, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, ul, i, center, fieldset, form, label, legend, caption {
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 100%;
            vertical-align: baseline;
            background: transparent;
        }

        ul {
            list-style-type: none;
            padding-left: 12px;
            }
        li{
            margin: 2px;
        }

        a{
            text-decoration: none !important;
        }

        #jimski {
            background-color: aquamarine !important;
        }

        #sidebar{
            font-size:14px;
        }
        
        .container{
            margin: 3%;
        }

        .container1{
            margin: 3%;
        }
        .container2{
            margin-top: 3%;
        }

        #book-title{
            margin-bottom:5%;
        }

        .branding {
            text-transform: uppercase;
            margin-bottom: 10px;
            }

            .branding .logo {
            font-size: 28px;
            margin-top: 0;
            margin-bottom: 0;
            }

            .branding .logo a {
            text-decoration: none;
            }

            /* .branding .text-highlight {
            color: #40babd;
            } */
        

            /* .codex{
                margin-top:3px;
                margin-top:3px;
            }

            .headings{
                margin-top:7px;
                margin-bottom:7px;

            } */

    </style>

</head> 

<body>
    <div>
                <!-- ******Header****** -->
        <header class="header">
            <div class="container2">
                <div id="jimmy" class="d-flex flex-row justify-content-center">
                    <div class="d-flex flex-column">
                        <div class="branding">
                            <h1 class="logo">
                                <i style="color:#006994;" class="far fa-file-alt"></i>
                                <span><b>Code of Canon Law</b></span>
                            </h1>
                        </div><!--//branding-->
                        <div>
                            <p>The 1917 Pio-Benedictine Code of Canon Law.</p>
                        </div><!--//tagline-->
                        
                        <div class="main-search-box pt-3 pb-4 d-inline-block">
                            <form class="form-inline search-form justify-content-center" action="/canon-search" method="get">
                        
                                <input type="text" placeholder="Search all canons..." name="search" class="form-control search-input">
                                
                                <button type="submit" class="btn search-btn" value="Search"><i class="fas fa-search"></i></button>
                                
                            </form>
                        </div>
                    </div>
                </div>
            </div><!--//container-->
        </header><!--//header-->
        <hr>
            <div class="container1">
                
                <div class="row">

                <!--CODEX CONTENT-->
                    <div class="doc-content col-md-8 col-12 order-1">
                        <div id="book-title"><h3>Results:</h3></div>
                        <div>
                            {% for result in data  %}
                            
                            <p><b>{{result.canon}}: </b>{{result.content}}</p>

                            {% endfor %}

                        </div>
                    </div><!--//react doc-content-->
                <!--CODEX CONTENT-->
                    
                
                    <div class="col-md-4 col-12 order-0 d-none d-md-flex">
                        <div class="container">
                        <ul id="sidebar" class="nav flex-column">
                            <li class="nav-item"><a href="#book-1_general-principles-of-canon-law"><b>Book I:</b> General Principles</a></li>
                            <li class="nav-item"><a href="#book-1_general-principles-of-canon-law"><b>Book II:</b> General Principles</a></li>
                            <!-- <li class="nav-item"><a href="#book-1_general-principles-of-canon-law"><b>Book I:</b> General Principles</a></li>
                            <li class="nav-item"><a href="#book-1_general-principles-of-canon-law"><b>Book I:</b> General Principles</a></li>
                            <li class="nav-item"><a href="#book-1_general-principles-of-canon-law"><b>Book I:</b> General Principles</a></li> -->
                        </div><!-- //doc-sidebar -->
                    </div>



                </div><!--//doc-body-->              
            </div><!--//container-->

<!--  END CONTENT   -->

    </div><!--//page-wrapper-->
    
    <footer >
        <div>
            <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <!-- <small class="copyright">Iudica Me 2020</small> -->
            
        </div><!--//container-->
    </footer><!--//footer-->
    
     
    <!-- Main Javascript -->          
    <script type="text/javascript" src={% static "assets/plugins/jquery-3.4.1.min.js" %}></script>
    <script type="text/javascript" src={% static "assets/plugins/bootstrap/js/bootstrap.min.js" %}></script>
    <script type="text/javascript" src={% static "assets/plugins/prism/prism.js" %}></script>    
    <script type="text/javascript" src={% static "assets/plugins/jquery-scrollTo/jquery.scrollTo.min.js" %}></script>      
    <script type="text/javascript" src={% static "assets/plugins/stickyfill/dist/stickyfill.min.js" %}></script>                                                             
    <script type="text/javascript" src={% static "assets/js/_main.js" %}></script>
    <!-- <script type="text/javascript" src={% static "assets/js/main.js" %}></script> -->
    
</body>
</html> 

codex/fcontent/templates/fcontent/index1.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>1917 Codex</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="David Lanigan dav.lanigan@gmail.com">    
    <link rel="shortcut icon" href="favicon.ico">  
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel='stylesheet' type='text/css'>
    <!-- FontAwesome JS -->
    <script defer src={% static "assets/fontawesome/js/all.js" %}></script>
    <!-- Global CSS -->
    <link rel="stylesheet" href={% static "assets/plugins/bootstrap/css/bootstrap.min.css" %}>   
    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href={% static "assets/css/styles.css" %}>
    
    <style>

        html, body, div, span, applet, object, iframe, blockquote, pre, a, abbr, acronym, address, big, cite, code, del, dfn, em, font, img, ins, kbd, q, s, samp, small, strike, strong, sub, sup, tt, var, b, u, ul, i, center, fieldset, form, label, legend, caption {
            margin: 0;
            padding: 0;
            border: 0;
            outline: 0;
            font-size: 100%;
            vertical-align: baseline;
            background: transparent;
        }

        ul {
            list-style-type: none;
            padding-left: 12px;
            }
        li{
            margin: 2px;
        }

        a{
            text-decoration: none !important;
        }

        #jimski {
            background-color: aquamarine !important;
        }

        #sidebar{
            font-size:14px;
        }
        
        .container{
            margin: 3%;
        }

        .container1{
            margin: 3%;
        }
        .container2{
            margin-top: 3%;
        }

        #book-title{
            margin-bottom:5%;
        }

        .branding {
            text-transform: uppercase;
            margin-bottom: 10px;
            }

            .branding .logo {
            font-size: 28px;
            margin-top: 0;
            margin-bottom: 0;
            }

            .branding .logo a {
            text-decoration: none;
            }

            /* .branding .text-highlight {
            color: #40babd;
            } */
        

            /* .codex{
                margin-top:3px;
                margin-top:3px;
            }

            .headings{
                margin-top:7px;
                margin-bottom:7px;

            } */

    </style>

</head> 

<body>
    <div>
                <!-- ******Header****** -->
        <header class="header">
            <div class="container2">
                <div id="jimmy" class="d-flex flex-row justify-content-center">
                    <div class="d-flex flex-column">
                        <div class="branding">
                            <h1 class="logo">
                                <i style="color:#006994;" class="far fa-file-alt"></i>
                                <span><b>Code of Canon Law</b></span>
                            </h1>
                        </div><!--//branding-->
                        <div>
                            <p>The 1917 Pio-Benedictine Code of Canon Law.</p>
                        </div><!--//tagline-->
                        
                        <div class="main-search-box pt-3 pb-4 d-inline-block">
                            <form class="form-inline search-form justify-content-center" action="/canon-search" method="get">
                        
                                <input type="text" placeholder="Search all canons..." name="search" class="form-control search-input">
                                
                                <button type="submit" class="btn search-btn" value="Search"><i class="fas fa-search"></i></button>
                                
                            </form>
                        </div>
                    </div>
                </div>
            </div><!--//container-->
        </header><!--//header-->
        <hr>
            <div class="container1">
                
                <div class="row">

                <!--CODEX CONTENT-->
                    <div class="doc-content col-md-8 col-12 order-1">
                        <div id="book-title"><h1>The First Book</h1></div>
                        <div id="app"></div>
                    </div><!--//react doc-content-->
                <!--CODEX CONTENT-->
                    
                
                    <div class="col-md-4 col-12 order-0 d-none d-md-flex">
                        <div class="container">
                        <ul id="sidebar" class="nav flex-column">
                            <li class="nav-item">
                                <span>
                                    <a href="#book-1_general-principles-of-canon-law"><b>Book I:</b> General Principles</a>
                                    <i data-toggle="collapse" data-target="#collapse1" class="fas fa-angle-down"></i>
                                </span>
                                
                                <ul class="collapse" id="collapse1">
                                    <li class="nav-item"><a href="#title-1_principles-of-ecclesiastical-laws">Title I: Principles of Ecclesiastical Laws</a></li>
                                    <li class="nav-item"><a href="#title-2_customs">Title II: Customs</a></li>
                                    <li class="nav-item"><a href="#title-3_manner-of-reckoning-time">Title III: Manner of Reckoning</a></li>
                                    <li class="nav-item"><a href="#title-4_rescripts">Title IV: Rescripts</a></li>
                                    <li class="nav-item"><a href="#title-5_privileges">Title V: Privileges</a></li>
                                </ul><!--//nav-->
                            </li>
                            
                            <li class="nav-item"><a href="{% url 'fcontent:book2' %}"><b>Book II:</b> Laws Concerning Persons</a></li>
                        </div><!-- //doc-sidebar -->
                    </div>



                </div><!--//doc-body-->              
            </div><!--//container-->

<!--  END CONTENT   -->

    </div><!--//page-wrapper-->
    
    <footer >
        <div>
            <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <!-- <small class="copyright">Iudica Me 2020</small> -->
            
        </div><!--//container-->
    </footer><!--//footer-->
    
     
    <!-- Main Javascript -->          
    <script type="text/javascript" src={% static "assets/plugins/jquery-3.4.1.min.js" %}></script>
    <script type="text/javascript" src={% static "assets/plugins/bootstrap/js/bootstrap.min.js" %}></script>
    <script type="text/javascript" src={% static "assets/plugins/prism/prism.js" %}></script>    
    <script type="text/javascript" src={% static "assets/plugins/jquery-scrollTo/jquery.scrollTo.min.js" %}></script>      
    <script type="text/javascript" src={% static "assets/plugins/stickyfill/dist/stickyfill.min.js" %}></script>                                                             
    <script type="text/javascript" src={% static "assets/js/_main.js" %}></script>
    <script type="text/javascript" src={% static "assets/js/i1/main.js" %}></script>
    
</body>
</html> 

codex/fcontent/templates/old/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap 4 project documentation theme for developers</title>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">    
    <link rel="shortcut icon" href="favicon.ico">  
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- FontAwesome JS -->
    <script defer src="assets/fontawesome/js/all.js"></script>
    <!-- Global CSS -->
    <link rel="stylesheet" href="assets/plugins/bootstrap/css/bootstrap.min.css">   
    <!-- Plugins CSS -->    
    <link rel="stylesheet" href="assets/plugins/elegant_font/css/style.css">    
    <!-- Theme CSS -->
    <link id="theme-style" rel="stylesheet" href="assets/css/styles.css">

</head> 

<body class="landing-page">   
	
	<!-- GITHUB BUTTON JS -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>
     
    <!--FACEBOOK LIKE BUTTON JAVASCRIPT SDK-->
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v6.0&appId=994736563909741&autoLogAppEvents=1"></script>
    
    <div class="page-wrapper">
        
        <!-- ******Header****** -->
        <header class="header text-center">
            <div class="container">
                <div class="branding">
                    <h1 class="logo">
                        <span aria-hidden="true" class="icon_documents_alt icon"></span>
                        <span class="text-highlight">Pretty</span><span class="text-bold">Docs</span>
                    </h1>
                </div><!--//branding-->
                <div class="tagline">
                    <p>Free Bootstrap 4 theme for your project documentation</p>
                    <p>Designed with <i class="fas fa-heart"></i> for developers</p>
                </div><!--//tagline-->
                
	             <div class="main-search-box pt-3 pb-4 d-inline-block">
	                 <form class="form-inline search-form justify-content-center" action="" method="get">
	            
			            <input type="text" placeholder="Enter search terms..." name="search" class="form-control search-input">
			            
			            <button type="submit" class="btn search-btn" value="Search"><i class="fas fa-search"></i></button>
			            
			        </form>
	             </div>
                 
                <div class="social-container">
	                <!-- Replace with your Github Button -->
	                <div class="github-btn mb-2">
						<a class="github-button" href="https://github.com/xriley/PrettyDocs-Theme" data-size="large" aria-label="Star xriley/PrettyDocs-Theme on GitHub">Star</a>
                        <a class="github-button" href="https://github.com/xriley" data-size="large" aria-label="Follow @xriley on GitHub">Follow @xriley</a>
	                </div>
	                <!-- Replace with your Twitter Button -->
                    <div class="twitter-tweet">
                        <a href="https://twitter.com/3rdwave_themes?ref_src=twsrc%5Etfw" class="twitter-follow-button" data-show-count="false">Follow @3rdwave_themes</a><script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
                    </div><!--//tweet-->
                    <!-- Replace with your Facebook Button -->
                    <div class="fb-like" data-href="https://themes.3rdwavemedia.com/" data-width="" data-layout="button_count" data-action="like" data-size="small" data-share="true"></div>         
                 </div><!--//social-container-->
                 
                
            </div><!--//container-->
        </header><!--//header-->
        
        <section class="cards-section text-center">
            <div class="container">
                <h2 class="title">Getting started is easy!</h2>
                <div class="intro">
                    <p>Welcome to prettyDocs. This landing page is an example of how you can use a card view to present segments of your documentation. You can customise the icon fonts based on your needs.</p>
                    <div class="cta-container">
                        <a class="btn btn-primary btn-cta" href="https://themes.3rdwavemedia.com/bootstrap-templates/startup/prettydocs-free-bootstrap-theme-for-developers-and-startups/" target="_blank"><i class="fas fa-cloud-download-alt"></i> Download Now</a>
                    </div><!--//cta-container-->
                </div><!--//intro-->
                <div id="cards-wrapper" class="cards-wrapper row">
                    <div class="item item-green col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <i class="icon fa fa-paper-plane"></i>
                            </div><!--//icon-holder-->
                            <h3 class="title">Quick Start</h3>
                            <p class="intro">Demo example, consectetuer adipiscing elit</p>
                            <a class="link" href="start.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-pink item-2 col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_puzzle_alt"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Components</h3>
                            <p class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit</p>
                            <a class="link" href="components.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-blue col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_datareport_alt"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Charts</h3>
                            <p class="intro">Lorem ipsum dolor sit amet, consectetuer adipiscing elit</p>
                            <a class="link" href="charts.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-purple col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_lifesaver"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">FAQs</h3>
                            <p class="intro">Layout for FAQ page. Lorem ipsum dolor sit amet, consectetuer adipiscing elit</p>
                            <a class="link" href="faqs.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-primary col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_genius"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">Showcase</h3>
                            <p class="intro">Layout for showcase page. Lorem ipsum dolor sit amet, consectetuer adipiscing elit </p>
                            <a class="link" href="showcase.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                    <div class="item item-orange col-lg-4 col-6">
                        <div class="item-inner">
                            <div class="icon-holder">
                                <span aria-hidden="true" class="icon icon_gift"></span>
                            </div><!--//icon-holder-->
                            <h3 class="title">License &amp; Credits</h3>
                            <p class="intro">Layout for license &amp; credits page. Consectetuer adipiscing elit.</p>
                            <a class="link" href="license.html"><span></span></a>
                        </div><!--//item-inner-->
                    </div><!--//item-->
                </div><!--//cards-->
                
            </div><!--//container-->
        </section><!--//cards-section-->
    </div><!--//page-wrapper-->
    
    <footer class="footer text-center">
        <div class="container">
            <!--/* This template is free as long as you keep the footer attribution link. If you'd like to use the template without the attribution link, you can buy the commercial license via our website: themes.3rdwavemedia.com Thank you for your support. :) */-->
            <small class="copyright">Designed with <i class="fas fa-heart"></i> by <a href="https://themes.3rdwavemedia.com/" target="_blank">Xiaoying Riley</a> for developers</small>
            
        </div><!--//container-->
    </footer><!--//footer-->
    
     
    <!-- Main Javascript -->          
    <script type="text/javascript" src="assets/plugins/jquery-3.4.1.min.js"></script>
    <script type="text/javascript" src="assets/plugins/bootstrap/js/bootstrap.min.js"></script>     
    <script type="text/javascript" src="assets/plugins/stickyfill/dist/stickyfill.min.js"></script>                                                                
    <script type="text/javascript" src="assets/js/main.js"></script>
    
</body>
</html> 